### PR TITLE
feat: epoll based worker

### PR DESCRIPTION
**Pull request by steve-chavez**
This replaces the usage of [curl_multi_perform](https://curl.se/libcurl/c/curl_multi_perform.html) (which uses `select()`) for [curl_multi_socket_action](https://curl.se/libcurl/c/curl_multi_socket_action.html) + `epoll()`, which is more performant (requests finish in less time) and more reliable (with 0 timeouts). 

It solves #86. Using the cloud test added on https://github.com/supabase/pg_net/pull/150, on this branch we get the following results:

```
postgres=# call repro_timeouts(10000);
NOTICE:  Waiting until 10000 requests complete
NOTICE:  Stats: {"request_successes":10000,"request_failures":0,"last_failure_error":null}
NOTICE:  Time taken: 00:01:01.360567
CALL

postgres=# call repro_timeouts(20000);
NOTICE:  Waiting until 20000 requests complete
NOTICE:  Stats: {"request_successes":20000,"request_failures":0,"last_failure_error":null}
NOTICE:  Time taken: 00:01:44.942479

postgres=# call repro_timeouts(100000);
NOTICE:  Waiting until 100000 requests complete
NOTICE:  Stats: {"request_successes":100000,"request_failures":0,"last_failure_error":null}
NOTICE:  Time taken: 00:08:58.325675

postgres=# call repro_timeouts (1000000);
NOTICE:  Waiting until 1000000 requests complete
NOTICE:  Stats: {"request_successes":1000000,"request_failures":0,"last_failure_error":null}
NOTICE:  Time taken: 01:45:33.085331
CALL
```

On master:

```
postgres=# call repro_timeouts(10000);
NOTICE:  Waiting until 10000 requests complete
NOTICE:  Stats: {"request_successes":8886,"request_failures":1114,"last_failure_error":"Ti
meout was reached"}
NOTICE:  Time taken: 00:01:44.061517
CALL
postgres=# call repro_timeouts(20000);
NOTICE:  Waiting until 20000 requests complete
NOTICE:  Stats: {"request_successes":18071,"request_failures":1929,"last_failure_error":"T
imeout was reached"}
NOTICE:  Time taken: 00:04:05.716657
CALL

postgres=# call repro_timeouts(30000);
NOTICE:  Waiting until 30000 requests complete
NOTICE:  Stats: {"request_successes":26939,"request_failures":3061,"last_failure_error":"T
imeout was reached"}
NOTICE:  Time taken: 00:06:31.642828
CALL
```

So we get 0 timeouts on 1M requests, while on master we got many failures starting at 10K requests. The completion of the requests take much less time as well.

### CODE REVIEW

**Comment by steve-chavez** [comment]
https://github.com/supabase/pg_net/pull/149 should be merged before but this is now ready for review.

I'm not closing https://github.com/supabase/pg_net/issues/86 once this is merged since I can no longer reproduce it locally (https://github.com/supabase/pg_net/issues/86#issuecomment-2344419986). But this should be an improvement nonetheless.

**Comment by steve-chavez** [comment]
Just to confirm this solves #86. On this branch we get the following results:

```
postgres=# call repro_timeouts(10000);
NOTICE:  Waiting until 10000 requests complete
NOTICE:  Stats: {"request_successes":10000,"request_failures":0,"last_failure_error":null}
NOTICE:  Time taken: 00:01:01.360567
CALL

postgres=# call repro_timeouts(20000);
NOTICE:  Waiting until 20000 requests complete
NOTICE:  Stats: {"request_successes":20000,"request_failures":0,"last_failure_error":null}
NOTICE:  Time taken: 00:01:44.942479

postgres=# call repro_timeouts(100000);
NOTICE:  Waiting until 100000 requests complete
NOTICE:  Stats: {"request_successes":100000,"request_failures":0,"last_failure_error":null}
NOTICE:  Time taken: 00:08:58.325675
```

On master:

```
postgres=# call repro_timeouts(10000);
NOTICE:  Waiting until 10000 requests complete
NOTICE:  Stats: {"request_successes":8886,"request_failures":1114,"last_failure_error":"Ti
meout was reached"}
NOTICE:  Time taken: 00:01:44.061517
CALL
postgres=# call repro_timeouts(20000);
NOTICE:  Waiting until 20000 requests complete
NOTICE:  Stats: {"request_successes":18071,"request_failures":1929,"last_failure_error":"T
imeout was reached"}
NOTICE:  Time taken: 00:04:05.716657
CALL

postgres=# call repro_timeouts(30000);
NOTICE:  Waiting until 30000 requests complete
NOTICE:  Stats: {"request_successes":26939,"request_failures":3061,"last_failure_error":"T
imeout was reached"}
NOTICE:  Time taken: 00:06:31.642828
CALL
```

So we get 0 timeouts on 1M requests, while on master we got many failures starting at 10K requests.

**Comment by steve-chavez** [comment]
FYI, there's a sporadic bug on libcurl that leads to some reqs failed: https://github.com/curl/curl/issues/14976

Will put this back to draft until it's resolved.

**Comment by steve-chavez** [comment]
https://github.com/curl/curl/issues/15079 was solved. It was mostly a lack of documentation. In essence, `curl_multi_cleanup` shouldn't be done frequently or the curl connection cache will be invalidated. So this should be good to go now.

**Review by soedirgo — APPROVED** [review]
epoll is Linux-only so can't test on my Mac; rubber stamping this

**Comment by steve-chavez** [comment]
> epoll is Linux-only so can't test on my Mac; rubber stamping this

Will open an issue to address this.

**Comment by TheOtherBrian1** [comment]
Should this be counted as a version change?

**Comment by riderx** [comment]
Can't wait this get release in Supabase cloud !

**Comment by steve-chavez** [comment]
> epoll is Linux-only so can't test on my Mac; rubber stamping this

Done on https://github.com/supabase/pg_net/pull/165

**Pull request merged**
